### ISSUE TITLE
Jobs are "Done" but still running

### ISSUE THREAD

**Issue by jblezoray** [matchID-project/frontend#71]
All the jobs that I run appear as "done" but are in fact still running.  

For instance, in this screen cap the "dataprep_deaths" is listed as "finis" (done) but the logs are still going on : 
![captureb](https://user-images.githubusercontent.com/882459/37147476-5d06e3bc-22c7-11e8-8a42-786ef9a240a7.png)

On this one, we the that the job is listed as "Done" under the "Jobs" drop list, but as running on the top-left of the status bar : 
![capturea](https://user-images.githubusercontent.com/882459/37147539-889b3690-22c7-11e8-8236-63c3b66dccb2.png)

## My configuration : 

**MatchId project**
branch Master, commit  11a7bc171c6 (Merge pull request #110 from matchID-project/dev)

**Exemple project**
branch Master, commit 620b0c3424d7713 (Update README.md)

**Host**
Linux jblezoray-pc 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**docker**
```
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                      PORTS                NAMES
ecdfbc4433b3        nginx                                                     "nginx -g 'daemon of…"   37 minutes ago      Up 37 minutes               0.0.0.0:80->80/tcp   matchid-nginx
5e638b45cd51        matchid-backend:latest                                    "./code/api.py"          37 minutes ago      Up 37 minutes               8081/tcp             matchid-backend
885b54fe85d6        kibana:latest                                             "/docker-entrypoint.…"   37 minutes ago      Up 37 minutes               5601/tcp             matchid-kibana
c9b79c417cfb        docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2   "/usr/local/bin/dock…"   37 minutes ago      Up 37 minutes               9200/tcp, 9300/tcp   matchid-esnode2
4c49123eb0e8        docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2   "/usr/local/bin/dock…"   37 minutes ago      Up 37 minutes               9200/tcp, 9300/tcp   matchid-esnode3
4496c0a80436        docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2   "/usr/local/bin/dock…"   37 minutes ago      Up 37 minutes               9200/tcp, 9300/tcp   matchid-elasticsearch
ca559468544f        matchid-frontend:latest                                   "npm run build"          38 minutes ago      Exited (0) 37 minutes ago                        matchid-build-front
```

**Comment by rhanka** [comment]
Thanx a lot for this detailed bug description.
Jobs supervision have been a pain in the ass, because of multithreading and parallelization. Now jobs status are computed from the log files and are more reliable.
