### ISSUE TITLE
Name of files for import

### ISSUE THREAD

**Issue by guillim** [matchID-project/frontend#72]
On the page https://matchid-project.github.io/tutorial

If we download several times the file 
![screen shot 2018-03-28 at 15 35 29](https://user-images.githubusercontent.com/13087916/38032345-b1605926-329d-11e8-8f8a-aae6855219d2.png)

deaths.txt.gz 
It may end automatically named
deaths (1).txt.gz
Which may be problematic... special character can suck for file naming

**Comment by rhanka** [comment]
this is fixed
now back and front just normalize the names the same way
